// Generated by Wrangler on Sun Apr 28 2024 10:26:50 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	ENVIRONMENT: string;
	SENDGRID_API_KEY: string;
	SENDGRID_EMAIL_RECIPIENT: string;
	SENDGRID_EMAIL_SENDER: string;
	DB: D1Database;
}
